apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ansible
  template:
    metadata:
      labels:
        app: ansible
    spec:
      containers:
        - name: ansible
          image: ansible-from-scratch
          command: ["sleep"]
          args: ["infinity"]